/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Ghost.gltf -o src/components/Ghost.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ghost(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Ghost.gltf')
  const { actions } = useAnimations(animations, group)

  // idle animation
  useEffect(() => {
    actions["Flying_Idle"].reset().fadeIn(0.5).play();
    return () => actions["Flying_Idle"].fadeOut(0.5)
  }, [])

  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          {/* ghost mesh */}
          <skinnedMesh name="Ghost" geometry={nodes.Ghost.geometry} material={materials.Atlas} skeleton={nodes.Ghost.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Ghost.gltf')
